apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-predictor
  labels:
    app: insurance-predictor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insurance-predictor
  template:
    metadata:
      labels:
        app: insurance-predictor
    spec:
      containers:
        - name: insurance-predictor
          image: 937387180258.dkr.ecr.us-east-1.amazonaws.com/ml/insurance-predictor:v1
          ports:
          - containerPort: 8000
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20

